services:

  Marvin255\RandomStringGenerator\Generator\RandomStringGenerator:
    class: Marvin255\RandomStringGenerator\Generator\DummyRandomStringGenerator
    arguments:
        - '%marvin255_random_string_generator.dummy_string%'
