services:

  Marvin255\RandomStringGenerator\RandomStringGenerator\RandomStringGenerator:
    class: Marvin255\RandomStringGenerator\RandomStringGenerator\DummyRandomStringGenerator
    arguments:
        - '%marvin255_random_string_generator.dummy_string%'
