services:

  Marvin255\RandomStringGenerator\RandomEngine\RandomEngine:
    class: Marvin255\RandomStringGenerator\RandomEngine\MtRandomEngine

  Marvin255\RandomStringGenerator\Generator\RandomStringGenerator:
    class: Marvin255\RandomStringGenerator\Generator\BasicRandomStringGenerator
    arguments:
      - '@Marvin255\RandomStringGenerator\RandomEngine\RandomEngine'
