services:

  Marvin255\RandomStringGenerator\RandomEngine\RandomEngine:
    class: Marvin255\RandomStringGenerator\RandomEngine\MtRandomEngine

  Marvin255\RandomStringGenerator\RandomStringGenerator\RandomStringGenerator:
    class: Marvin255\RandomStringGenerator\RandomStringGenerator\BasicRandomStringGenerator
    arguments:
      - '@Marvin255\RandomStringGenerator\RandomEngine\RandomEngine'
